language: bash

services:
  - docker

env:
  global:
    - BASE_IMAGE_STABILITY_TAG=4.6.0
  matrix:
    - WORDPRESS=4 PHP_VER=7.2 TAGS=4-7.2,4,latest
    - WORDPRESS=4 PHP_VER=7.1 TAGS=4-7.1
    - WORDPRESS=4 PHP_VER=7.0 TAGS=4-7.0
    - WORDPRESS=4 PHP_VER=5.6 TAGS=4-5.6

script:
  - set -e
  - cd "${WORDPRESS}"
  - make check-configs
  - make
  - make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
